import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sideline Photography</title>
        <meta name="description" content="Generated by Web Wave Designs"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-rose-800 h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1>Sideline Photography</h1>
            <ul>
              <li>
                <BsFillMoonStarsFill />
                <a href="">Thing 1</a>
              </li>
              <li><a href="">Thing 2</a></li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  );
}
